name: CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: pescel/ab3-simple-typescript:latest

      - name: Echo Deployment success
        run: echo "Deployment erfolgreich abgeschlossen"
